(function(){
function s(n,v){var e=document.querySelector('[name="'+n+'"]');if(!e)return;
if(e.tagName==="SELECT"){for(var i=0;i<e.options.length;i++){if(e.options[i].value===v||e.options[i].text===v){e.selectedIndex=i;e.dispatchEvent(new Event("change",{bubbles:true}));return;}}}
else{e.value=v;e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));}}
function r(n,v){var rs=document.querySelectorAll('input[type="radio"][name="'+n+'"]');for(var i=0;i<rs.length;i++){if(rs[i].value===v){rs[i].checked=true;rs[i].dispatchEvent(new Event("change",{bubbles:true}));}}}
function c(n,v){var e=document.querySelector('[name="'+n+'"]');if(e){e.checked=v;e.dispatchEvent(new Event("change",{bubbles:true}));}}
s("TextBoxEmail","feng@innora.ai");
s("TextBoxCveIds","3");
s("DropDownListRequestType","Single");

// === CVE-1 (Batch2): Null IV in CBC-mode Across Payment/Auth/Security Subsystems ===
s("RepeaterSingleForms$ctl00$TextBoxVendor","Ant Group (Alibaba)");
s("RepeaterSingleForms$ctl00$RepeaterProductVersion$ctl01$TextBoxProdCodeBase","Alipay");
s("RepeaterSingleForms$ctl00$RepeaterProductVersion$ctl01$TextBoxVersions","10.8.30.8000 and prior (Android)");
s("RepeaterSingleForms$ctl00$TextBoxAffectedComponents","CBC-mode cryptographic implementations across multiple subsystems: (1) DesEncrypt (com.alipay.android.phone.offlinepay.encrypt.DesEncrypt:47) — offline payment DES/CBC, (2) TriDesCBC (com.alipay.mobile.verifyidentity.log.utils.TriDesCBC:64,102) — identity verification 3DES/CBC, (3) TriDesCBC (com.alipay.android.msp.framework.encrypt.TriDesCBC:36,57) — MSP payment framework 3DES/CBC, (4) TriDesCBC (com.alipay.mobile.phone.deviceauth.util.TriDesCBC:65,103) — device authentication 3DES/CBC, (5) AesCrypto (com.alipay.apmobilesecuritysdk.tool.crypto.AesCrypto:76,108) — SecurityGuard SDK AES/CBC, (6) AESUtils (com.alipay.xmedia.common.biz.utils.AESUtils:722), (7) FCDataPrivacyUtil (com.alipay.mobile.flowcustoms.engine.FCDataPrivacyUtil:98) — privacy data, (8) FileSecurityTool (com.alipay.android.phone.mobilecommon.multimediabiz.biz.file.FileSecurityTool:496), (9) EncryptFileUtil (com.alipay.mobile.intelligentdecision.EncryptFileUtil:64,101) — AI decision files.");
s("RepeaterSingleForms$ctl00$TextBoxAttackVectors","1. All listed files initialize IvParameterSpec with all-zero byte arrays: new IvParameterSpec(new byte[8]) for DES/3DES or new IvParameterSpec(new byte[cipher.getBlockSize()]) for AES\\n2. A null IV in CBC mode causes the first block to be encrypted identically to ECB mode, leaking plaintext patterns\\n3. DesEncrypt.java:47 processes offline payment data with DES/CBC and null IV\\n4. AesCrypto.java:76,108 is part of the SecurityGuard SDK (apmobilesecuritysdk) — the security infrastructure itself uses null IV\\n5. Multiple TriDesCBC implementations share the same null IV pattern across identity verification and device authentication\\n6. NIST SP 800-38A Section 5.2 explicitly prohibits null or constant IVs in CBC mode");
s("RepeaterSingleForms$ctl00$TextBoxOwnDescription","The Alipay Android application v10.8.30.8000 contains a systematic use of null (all-zero) initialization vectors (IVs) in CBC-mode encryption across at least 10 source files spanning 4 critical functional domains: offline payment (DesEncrypt.java:47), identity verification (TriDesCBC.java:64,102), device authentication (TriDesCBC.java:65,103), and the SecurityGuard SDK itself (AesCrypto.java:76,108). Each file initializes IvParameterSpec with new byte[8] (DES/3DES) or new byte[cipher.getBlockSize()] (AES), producing all-zero IVs. In CBC mode, a null IV causes the encryption of the first plaintext block to be equivalent to ECB mode, enabling pattern analysis and chosen-plaintext attacks on the first block. The fact that the security SDK (apmobilesecuritysdk) itself uses null IVs represents a fundamental failure of the security infrastructure. CWE-329. CVSS 3.1: AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N (9.1).");
s("RepeaterSingleForms$ctl00$TextBoxDiscoverer","Jiqiang Feng (Innora AI Security Research)");
s("RepeaterSingleForms$ctl00$TextBoxReferences","https://github.com/sgInnora/alipay-securityguard-analysis\nhttps://innora.ai/zfb/privacy-analysis.html\nhttps://packetstormsecurity.com/files/217089");
s("RepeaterSingleForms$ctl00$TextBoxCveAddlInfo","Related to MITRE Tickets #2005801 and #2010319. NEW vulnerability class — systematic null IV usage across payment and authentication subsystems.\n\nAPK SHA-256: 2eebd18eb78b2bdcc737c568a8057345255b9660dbf6f5af83743644effcaad2\n\nEvidence files (10 files, exact line numbers):\n- DesEncrypt.java:47 (offline payment)\n- TriDesCBC.java:64,102 (identity verification)\n- TriDesCBC.java:36,57 (MSP payment)\n- TriDesCBC.java:65,103 (device auth)\n- AesCrypto.java:76,108 (SecurityGuard SDK)\n- AESUtils.java:722 (media)\n- FCDataPrivacyUtil.java:98 (privacy data)\n- FileSecurityTool.java:496 (file security)\n- EncryptFileUtil.java:64,101 (AI decision)\n\n5-round multi-LLM cross-validation: 5/5 APPROVE (Gemini, Cogito, DeepSeek, Gemini Flash, Kimi). Zero false positive detected.\n\nVendor notified 2026-02-25, classified as normal functionality 2026-03-10. Requesting MITRE CNA-LR.");
s("RepeaterSingleForms$ctl00$DropDownListVulnerabilityType","Other or Unknown");
s("RepeaterSingleForms$ctl00$TextBoxOtherVulnerabilityType","Not Using a Random IV with CBC Mode (CWE-329)");
s("RepeaterSingleForms$ctl00$DropDownListAttack","Remote");

// === CVE-2 (Batch2): Cleartext Login Token via Unprotected JSBridge ===
s("RepeaterSingleForms$ctl01$TextBoxVendor","Ant Group (Alibaba)");
s("RepeaterSingleForms$ctl01$RepeaterProductVersion$ctl01$TextBoxProdCodeBase","Alipay");
s("RepeaterSingleForms$ctl01$RepeaterProductVersion$ctl01$TextBoxVersions","10.8.30.8000 and prior (Android)");
s("RepeaterSingleForms$ctl01$TextBoxAffectedComponents","Nebula H5 Framework JSBridge — CommonInfoBridgeExtension (com.alipay.mobile.nebulax.integration.wallet.extensions.CommonInfoBridgeExtension:211,224,338) and TaConfigProviderExtendNoOp (com.alipay.multiplatform.phone.xriver_integration_api.impl.TaConfigProviderExtendNoOp:322). The getLoginToken() JSBridge method exposes the user login token to H5 pages.");
s("RepeaterSingleForms$ctl01$TextBoxAttackVectors","1. CommonInfoBridgeExtension.java:211 exposes getLoginToken() as a JSBridge method accessible to H5 pages loaded in WebView\\n2. CommonInfoBridgeExtension.java:338-341 implements permit() which returns null — no permission check on this sensitive API\\n3. TaConfigProviderExtendNoOp.java:322-325 implements shouldLoginTokenUseClearText() with default return value of true\\n4. CommonInfoBridgeExtension.java:224 reads the actual login token when shouldLoginTokenUseClearText() returns true\\n5. Line 226-227: token is placed in JSON with encrypted=false flag: {token: 'xxx', encrypted: false}\\n6. Attack chain: DeepLink (alipays://platformapi/startapp?appId=20000067&url=evil.com) loads malicious H5 page → page calls getLoginToken() JSBridge → permit() returns null (no auth) → cleartext token returned → session hijack");
s("RepeaterSingleForms$ctl01$TextBoxOwnDescription","The Alipay Android application v10.8.30.8000 exposes a getLoginToken() method through the Nebula H5 Framework JSBridge (CommonInfoBridgeExtension.java:211) that returns the user's login session token in cleartext to any H5 page loaded in the WebView. The method's permission guard (permit() at line 338) returns null, meaning no authorization check is performed. The configuration method shouldLoginTokenUseClearText() (TaConfigProviderExtendNoOp.java:322) defaults to returning true, causing the actual login token to be transmitted as plaintext JSON ({token:'...', encrypted:false}). Combined with the DeepLink URL scheme (alipays://platformapi/startapp?appId=20000067&url=), an attacker can load a malicious H5 page that calls this JSBridge method to steal the user's session token without any permission check. CWE-319, CWE-862. CVSS 3.1: AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:N (8.5).");
s("RepeaterSingleForms$ctl01$TextBoxDiscoverer","Jiqiang Feng (Innora AI Security Research)");
s("RepeaterSingleForms$ctl01$TextBoxReferences","https://github.com/sgInnora/alipay-securityguard-analysis\nhttps://innora.ai/zfb/privacy-analysis.html\nhttps://packetstormsecurity.com/files/217089");
s("RepeaterSingleForms$ctl01$TextBoxCveAddlInfo","Related to MITRE Tickets #2005801 and #2010319. NEW vulnerability class — JSBridge authorization bypass + cleartext token exposure.\n\nAPK SHA-256: 2eebd18eb78b2bdcc737c568a8057345255b9660dbf6f5af83743644effcaad2\n\nKey evidence:\n- CommonInfoBridgeExtension.java:211 — getLoginToken() JSBridge method\n- CommonInfoBridgeExtension.java:338-341 — permit() returns null\n- TaConfigProviderExtendNoOp.java:322-325 — shouldLoginTokenUseClearText() returns true\n- CommonInfoBridgeExtension.java:224-227 — cleartext token in JSON\n\nThis vulnerability chains with CVE-1 (DeepLink URL Scheme bypass, MITRE #2005801) to form a complete session hijack attack.\n\n5-round multi-LLM cross-validation: 5/5 APPROVE. Vendor notified 2026-02-25. Requesting MITRE CNA-LR.");
s("RepeaterSingleForms$ctl01$DropDownListVulnerabilityType","Incorrect Access Control");
s("RepeaterSingleForms$ctl01$DropDownListAttack","Remote");

// === CVE-3 (Batch2): PatchProxy Remote Disabling of TLS Certificate Validation ===
s("RepeaterSingleForms$ctl02$TextBoxVendor","Ant Group (Alibaba)");
s("RepeaterSingleForms$ctl02$RepeaterProductVersion$ctl01$TextBoxProdCodeBase","Alipay");
s("RepeaterSingleForms$ctl02$RepeaterProductVersion$ctl01$TextBoxVersions","10.8.30.8000 and prior (Android)");
s("RepeaterSingleForms$ctl02$TextBoxAffectedComponents","TLS/SSL security infrastructure controlled by PatchProxy hot-patching system: (1) ZSSLContextFactory.X509TrustManagerWrapper (com.alipay.mobile.common.transport.ssl.ZSSLContextFactory:37-65) — checkServerTrusted and checkClientTrusted methods, (2) ZApacheSSLSocketFactory (com.alipay.mobile.common.transport.ssl.ZApacheSSLSocketFactory:49-54) — HostnameVerifier, (3) AndroidWebViewClient.onReceivedSslError (com.alipay.mobile.nebulacore.android.AndroidWebViewClient:149) and 9+ additional WebViewClient implementations including cashier (payment) and zoloz (facial recognition) WebViews. Total: 50+ PatchProxy control points across SSL/TLS security stack.");
s("RepeaterSingleForms$ctl02$TextBoxAttackVectors","1. ZSSLContextFactory.java:63-65 — checkServerTrusted() is guarded by PatchProxy.proxy(); if PatchProxy returns isSupported=true, the actual certificate validation is SKIPPED\\n2. ZSSLContextFactory.java:54-56 — checkClientTrusted() has the same PatchProxy bypass\\n3. ZApacheSSLSocketFactory.java:49-54 — setHostnameVerifierV2() can be replaced by PatchProxy to inject AllowAllHostnameVerifier\\n4. AndroidWebViewClient.java:149 — onReceivedSslError() in the core Nebula WebView can be replaced to call sslErrorHandler.proceed()\\n5. Same pattern in cashier WebView (e.java:73), zoloz facial recognition WebView (b.java:79), and IDFace WebView (IDFaceWebViewClient.java:73)\\n6. ZSSLContextFactory.java contains 27 PatchProxy/ChangeQuickRedirect references total\\n7. Attack chain: Compromised patch server pushes patch → PatchProxy replaces checkServerTrusted → TLS MITM becomes possible on all connections");
s("RepeaterSingleForms$ctl02$TextBoxOwnDescription","The Alipay Android application v10.8.30.8000 implements its entire TLS/SSL security stack with PatchProxy (hot-patching) control points that allow remote replacement of security-critical methods. ZSSLContextFactory.X509TrustManagerWrapper (line 63-65) wraps the system TrustManager but guards checkServerTrusted() and checkClientTrusted() with PatchProxy.proxy() — if a remote patch returns isSupported=true, the actual certificate validation is bypassed. ZApacheSSLSocketFactory (line 49-54) allows the HostnameVerifier to be remotely replaced. Additionally, onReceivedSslError() in 10+ WebViewClient implementations (including payment cashier and facial recognition WebViews) can be remotely patched to call proceed() instead of cancel(). The file ZSSLContextFactory.java alone contains 27 PatchProxy references. This creates a remote TLS kill-switch: a compromised or coerced patch server operator can disable all certificate validation without user notification. CWE-295. CVSS 3.1: AV:N/AC:L/PR:H/UI:N/S:C/C:H/I:H/A:N (7.8).");
s("RepeaterSingleForms$ctl02$TextBoxDiscoverer","Jiqiang Feng (Innora AI Security Research)");
s("RepeaterSingleForms$ctl02$TextBoxReferences","https://github.com/sgInnora/alipay-securityguard-analysis\nhttps://innora.ai/zfb/privacy-analysis.html\nhttps://packetstormsecurity.com/files/217089");
s("RepeaterSingleForms$ctl02$TextBoxCveAddlInfo","Related to MITRE Tickets #2005801 (CVE-7: EmptyX509TrustManager) and #2010319. This is a DIFFERENT and MORE SEVERE vulnerability than CVE-7: CVE-7 is a static empty TrustManager implementation, while this vulnerability allows DYNAMIC remote replacement of working TrustManagers via hot-patching.\n\nAPK SHA-256: 2eebd18eb78b2bdcc737c568a8057345255b9660dbf6f5af83743644effcaad2\n\nAffected WebViewClients (SSL error handler PatchProxy-controlled):\n1. AndroidWebViewClient.java:149 (Nebula core)\n2. cashier/h5container/webview/sys/e.java:73 (PAYMENT)\n3. zoloz/toyger/workspace/b.java:79 (FACIAL RECOGNITION)\n4. IDFaceWebViewClient.java:73 (ID CARD RECOGNITION)\n5. mywebview/sdk/WebViewClient.java:183\n6. shareassist/WeiboAuthActivity.java:223\n7. LegacyCubeH5WebViewClientAdapter.java:228\n8. H5ViewClientAdapter.java:252\n9. H5WebDriverHelper.java:75\n10. h5container/uccore/e.java:71\n\n5-round multi-LLM cross-validation: 5/5 APPROVE. Vendor notified 2026-02-25. Requesting MITRE CNA-LR.");
s("RepeaterSingleForms$ctl02$DropDownListVulnerabilityType","Missing SSL Certificate Validation");
s("RepeaterSingleForms$ctl02$DropDownListAttack","Remote");

// === Checkbox必须勾选(静默必填!) ===
c("CheckBoxCnaVerified", true);
c("CheckBoxCveAssigned", true);

alert("Batch-2 CVE form filled! Review all 3 entries:\n1. Null IV (CWE-329, CVSS 9.1)\n2. Cleartext Token+No Auth JSBridge (CWE-319+862, CVSS 8.5)\n3. PatchProxy TLS Kill-Switch (CWE-295, CVSS 7.8)\n\nCheck all fields before submitting!");
})();
