#!/bin/bash
# sg_command_trace.sh — Map all SecurityGuard doCommandNative IDs from decompiled Java
# Usage: ./sg_command_trace.sh [decompiled_dir] [output_file]

set -euo pipefail

DECOMPILED_DIR="${1:-./sg_decompiled}"
OUTPUT="${2:-./analysis/command_map.md}"

if [ ! -d "$DECOMPILED_DIR" ]; then
    echo "ERROR: Decompiled directory not found: $DECOMPILED_DIR"
    echo "Run sg_decompile.sh first"
    exit 1
fi

echo "=== SecurityGuard Command ID Tracer ==="

mkdir -p "$(dirname "$OUTPUT")"

# Find all doCommand calls with their command IDs
echo "Scanning for doCommand calls..."

cat > "$OUTPUT" << 'HEADER'
# SecurityGuard Native Command ID Map

> Auto-generated by sg_command_trace.sh
> All commands route through: `JNICLibrary.doCommandNative(int commandId, Object... args)`

| Command ID | File | Context | Arguments |
|-----------|------|---------|-----------|
HEADER

grep -rn "doCommand(" "$DECOMPILED_DIR" --include="*.java" 2>/dev/null | while IFS= read -r line; do
    file=$(echo "$line" | cut -d: -f1 | sed "s|$DECOMPILED_DIR/||")
    lineno=$(echo "$line" | cut -d: -f2)
    code=$(echo "$line" | cut -d: -f3-)

    # Extract command ID (number after doCommand()
    cmd_id=$(echo "$code" | grep -oE 'doCommand\([0-9]+' | grep -oE '[0-9]+' | head -1)
    [ -z "$cmd_id" ] && continue

    # Extract arguments summary
    args=$(echo "$code" | sed 's/.*doCommand([0-9]*, //' | sed 's/);.*//' | head -c 80)

    echo "| $cmd_id | $file:$lineno | $(basename "$file" .java) | \`$args\` |"
done >> "$OUTPUT"

# Also scan the main APK jadx output if available
APK_JADX="${3:-}"
if [ -d "$APK_JADX" ]; then
    echo ""
    echo "Scanning main APK jadx output..."
    grep -rn "doCommand(" "$APK_JADX" --include="*.java" 2>/dev/null | while IFS= read -r line; do
        file=$(echo "$line" | cut -d: -f1 | sed "s|$APK_JADX/||")
        code=$(echo "$line" | cut -d: -f3-)
        cmd_id=$(echo "$code" | grep -oE 'doCommand\([0-9]+' | grep -oE '[0-9]+' | head -1)
        [ -z "$cmd_id" ] && continue
        echo "| $cmd_id | [APK] $file | $(basename "$file" .java) | |"
    done >> "$OUTPUT"
fi

# Sort by command ID
{
    head -7 "$OUTPUT"
    tail -n +8 "$OUTPUT" | sort -t'|' -k2 -n
} > "${OUTPUT}.tmp" && mv "${OUTPUT}.tmp" "$OUTPUT"

total=$(grep -c "^|" "$OUTPUT" | tr -d ' ')
echo ""
echo "Found $((total - 1)) command calls"
echo "Output: $OUTPUT"

# Generate component mapping
echo ""
echo "## Component Mapping" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "Command Range → Component:" >> "$OUTPUT"
echo "  10101      → SDK Initialization" >> "$OUTPUT"
echo "  10401      → SecureSignature (Request Signing)" >> "$OUTPUT"
echo "  10501      → DynamicDataEncrypt" >> "$OUTPUT"
echo "  10502-10503 → DynamicDataStore" >> "$OUTPUT"
echo "  10601      → StaticDataEncrypt" >> "$OUTPUT"
echo "  10602-10604 → StaticDataStore" >> "$OUTPUT"
echo "  10605      → StaticKeyEncrypt" >> "$OUTPUT"
echo "  10901      → DataCollection" >> "$OUTPUT"
echo "  11601      → OpenSDK" >> "$OUTPUT"
echo "  11901      → AtlasEncrypt" >> "$OUTPUT"
echo "  12101-12102 → SafeToken" >> "$OUTPUT"
echo "  12501-12504 → LiteVM/AVMP (Bytecode VM)" >> "$OUTPUT"
echo "  12605-12611 → EdgeComputing" >> "$OUTPUT"
echo "  12801      → Compat" >> "$OUTPUT"
echo "  13701-13702 → DataReport" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
